version: '2'
services:
  web:
    extends:
      file: docker-compose-base.yml
      service: base
    env_file:
      - conf/production.env
    command: sh -c " cabot migrate && gunicorn cabot.wsgi:application -b 0.0.0.0:5000 --workers=5"
    ports:
      - "5000:5000"
    links:
      - redis
      - db

  worker:
    extends:
      file: docker-compose-base.yml
      service: base
    env_file:
      - conf/production.env
    command: celery worker -A cabot --concurrency=16 -Ofair
    environment:
      - SKIP_INIT=1
      - WAIT_FOR_MIGRATIONS=1
    links:
      - redis
      - db

  beat:
    extends:
      file: docker-compose-base.yml
      service: base
    env_file:
      - conf/production.env
    command: celery beat -A cabot
    environment:
      - SKIP_INIT=1
      - WAIT_FOR_MIGRATIONS=1
    links:
      - redis
      - db

  redis:
    image: redis:alpine
    command: redis-server --requirepass tryme
    restart: always

  db:
    image: postgres:9.6-alpine
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

volumes:
    data:
